networks:
  userdbnw:

services:
  db:
    image: mongo
    # restart: always
    # env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_U}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
    networks:
      - userdbnw
    ports:
      - 27017:27017
    volumes:
      - ./data/database:/data/db

  mongo-express:
    image: mongo-express
    # restart: always
    depends_on:
      - db
    networks:
      - userdbnw
    ports:
      - 8081:8081
    # env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_U}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PWD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_U}:${MONGO_ROOT_PWD}@db:27017/

  authenticator:
    build: ./Authenticator
    environment:
      MONGO_ROOT_U: ${MONGO_ROOT_U}
      MONGO_ROOT_PWD: ${MONGO_ROOT_PWD}
      MP4_DATABASE: ${MP4_DATABASE}
      MP4_ADMIN_PASS: ${MP4_ADMIN_PASS}
    networks:
      - userdbnw
    depends_on:
      - db
  
  token-manager:
    build: ./TokenManager
    environment:
      MONGO_ROOT_U: ${MONGO_ROOT_U}
      MONGO_ROOT_PWD: ${MONGO_ROOT_PWD}
      MP4_DATABASE: ${MP4_DATABASE}
      MP4_ADMIN_PASS: ${MP4_ADMIN_PASS}
    networks:
      - userdbnw
    depends_on:
      - db
